#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"  
 
RWTexture2D<float4> OutTexture;  
  
[numthreads(16, 16, 1)]
void MainCS(uint3 ThreadId : SV_DispatchThreadID)
{
	//Set up some variables we are going to need
    float sizeX, sizeY;
    OutTexture.GetDimensions(sizeX, sizeY);

    float2 iResolution = float2(sizeX, sizeY);
    float2 uv = (ThreadId.xy / iResolution.xy) - 0.5;


    OutTexture[ThreadId.xy]= float4(1.0,0.0,1.0,1.0);
}